# Generated by Django 2.1.2 on 2020-02-26 17:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('date_sequenced', models.DateField()),
                ('runfolder', models.CharField(max_length=50)),
                ('capture', models.IntegerField(choices=[(-1, 'U'), (1, 'Targeted'), (2, 'WGS'), (3, 'WES')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)])),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisVariant',
            fields=[
                ('av_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('depth', models.IntegerField()),
                ('analysis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Analysis')),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('criteria_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_code', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('interpretation_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('date_analysed', models.DateField()),
                ('pathogenicity', models.IntegerField(choices=[(1, 'Class 1 - Certain non-pathogenic variant'), (2, 'Class 2 - Likely non-pathogenic variant'), (3, 'Class 3 - Uncertain pathogenicity variant'), (4, 'Class 4 - Likely pathogenic variant'), (5, 'Class 5 - Certain pathogenic variant')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(5)])),
                ('active', models.BooleanField()),
                ('analysed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('analysis_variant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.AnalysisVariant')),
            ],
        ),
        migrations.CreateModel(
            name='InterpretationCriteria',
            fields=[
                ('ic_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('criteria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Criteria')),
                ('interpretation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Interpretation')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('proband', models.IntegerField(choices=[(0, 'N'), (1, 'Y'), (-1, 'U')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('affected_relatives', models.IntegerField(choices=[(0, 'N'), (1, 'Y'), (-1, 'U')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='RefGenome',
            fields=[
                ('genome_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('sample_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('sample_name', models.CharField(max_length=15)),
                ('workflow', models.IntegerField(choices=[(-1, 'U'), (1, 'Germline'), (2, 'Somatic')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(2)])),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('sample_type_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('sample_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sequencer',
            fields=[
                ('sequencer_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SomaticInformation',
            fields=[
                ('somatic_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.IntegerField()),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('variant_id_auto', models.AutoField(primary_key=True, serialize=False)),
                ('chrom', models.CharField(max_length=2)),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=15)),
                ('alt', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.SampleType'),
        ),
        migrations.AddField(
            model_name='sample',
            name='somatic_informaton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.SomaticInformation'),
        ),
        migrations.AddField(
            model_name='analysisvariant',
            name='genome_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.RefGenome'),
        ),
        migrations.AddField(
            model_name='analysisvariant',
            name='variant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Variant'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sample_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Sample'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='sequencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='somethingsnappydb_app.Sequencer'),
        ),
    ]
