# Generated by Django 2.1.2 on 2020-02-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('somethingsnappydb_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='somatic_informaton',
            new_name='somatic_information',
        ),
    ]
