# Generated by Django 2.1.2 on 2020-02-27 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('somethingsnappydb_app', '0002_auto_20200227_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='raw_c',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='raw_g',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='raw_p',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
    ]
